return {}
-- return {
-- 	{ -- Autoformat
-- 		"stevearc/conform.nvim",
-- 		event = { "BufWritePre" },
-- 		cmd = { "ConformInfo" },
-- 		keys = {
-- 			{
-- 				"<C-f>",
-- 				function()
-- 					require("conform").format({ async = true, lsp_format = "fallback" })
-- 				end,
-- 				mode = "",
-- 				desc = "[F]ormat buffer",
-- 			},
-- 		},
-- 		opts = {
-- 			notify_on_error = false,
-- 			format_on_save = function(bufnr)
-- 				-- Disable "format_on_save lsp_fallback" for languages that don't
-- 				-- have a well standardized coding style. You can add additional
-- 				-- languages here or re-enable it for the disabled ones.
-- 				local disable_filetypes = { c = true, cpp = true }
-- 				if disable_filetypes[vim.bo[bufnr].filetype] then
-- 					return nil
-- 				else
-- 					return {
-- 						timeout_ms = 500,
-- 						lsp_format = "fallback",
-- 					}
-- 				end
-- 			end,
-- 			formatters_by_ft = {
-- 				lua = { "stylua" },
-- 				python = { "black" },
-- 				-- Conform can also run multiple formatters sequentially
-- 				-- python = { "isort", "black" },
-- 				--
-- 				-- You can use 'stop_after_first' to run the first available formatter from the list
-- 				-- javascript = { "prettierd", "prettier", stop_after_first = true },
-- 			},
-- 		},
-- 	},
--
-- 	{ -- Autocompletion
-- 		"saghen/blink.cmp",
-- 		event = "VimEnter",
-- 		version = "1.*",
-- 		dependencies = {
-- 			-- Snippet Engine
-- 			{
-- 				"L3MON4D3/LuaSnip",
-- 				version = "2.*",
-- 				build = (function()
-- 					-- Build Step is needed for regex support in snippets.
-- 					-- This step is not supported in many windows environments.
-- 					-- Remove the below condition to re-enable on windows.
-- 					if vim.fn.has("win32") == 1 or vim.fn.executable("make") == 0 then
-- 						return
-- 					end
-- 					return "make install_jsregexp"
-- 				end)(),
-- 				dependencies = {
-- 					-- `friendly-snippets` contains a variety of premade snippets.
-- 					--    See the README about individual language/framework/plugin snippets:
-- 					--    https://github.com/rafamadriz/friendly-snippets
-- 					{
-- 						"rafamadriz/friendly-snippets",
-- 						config = function()
-- 							require("luasnip.loaders.from_vscode").lazy_load()
-- 						end,
-- 					},
-- 				},
-- 				opts = {},
-- 			},
-- 			"folke/lazydev.nvim",
-- 		},
-- 		--- @module 'blink.cmp'
-- 		--- @type blink.cmp.Config
-- 		opts = {
-- 			keymap = {
-- 				preset = "none", -- we'll define our own
-- 				["<CR>"] = { "accept", "fallback" }, -- confirm selection
-- 				["<Tab>"] = { "select_next", "fallback" }, -- next suggestion
-- 				["<S-Tab>"] = { "select_prev", "fallback" }, -- previous suggestion
-- 				["<C-e>"] = { "hide" }, -- close menu
-- 				["<C-Space>"] = { "show" },
-- 				-- For more advanced Luasnip keymaps (e.g. selecting choice nodes, expansion) see:
-- 				--    https://github.com/L3MON4D3/LuaSnip?tab=readme-ov-file#keymaps
-- 			},
--
-- 			appearance = {
-- 				-- 'mono' (default) for 'Nerd Font Mono' or 'normal' for 'Nerd Font'
-- 				-- Adjusts spacing to ensure icons are aligned
-- 				nerd_font_variant = "mono",
-- 			},
--
-- 			completion = {
-- 				-- By default, you may press `<c-space>` to show the documentation.
-- 				-- Optionally, set `auto_show = true` to show the documentation after a delay.
-- 				documentation = { auto_show = false, auto_show_delay_ms = 500 },
-- 			},
--
-- 			sources = {
-- 				default = { "lsp", "path", "snippets", "lazydev" },
-- 				providers = {
-- 					lazydev = { module = "lazydev.integrations.blink", score_offset = 100 },
-- 				},
-- 			},
--
-- 			snippets = { preset = "luasnip" },
--
-- 			-- Blink.cmp includes an optional, recommended rust fuzzy matcher,
-- 			-- which automatically downloads a prebuilt binary when enabled.
-- 			--
-- 			-- By default, we use the Lua implementation instead, but you may enable
-- 			-- the rust implementation via `'prefer_rust_with_warning'`
-- 			--
-- 			-- See :h blink-cmp-config-fuzzy for more information
-- 			fuzzy = { implementation = "lua" },
--
-- 			-- Shows a signature help window while you type arguments for a function
-- 			signature = { enabled = true },
-- 		},
-- 	},
-- 	{
-- 		"windwp/nvim-autopairs",
-- 		event = "InsertEnter",
-- 		config = true,
-- 		-- use opts = {} for passing setup options
-- 		-- this is equivalent to setup({}) function
-- 	},
-- }
